export { default as NigeriaIcon } from '@/src/assets/icon/Nigeria.svg';
export { default as ClipboardIcon } from '@/src/assets/icon/Clipboardill.svg';
export { default as PlusIcon } from '@/src/assets/icon/addIcon-01.svg';
export { default as NoticeIcon } from '@/src/assets/icon/NoticeIcon.svg';
export { default as DashSquareIcon } from '@/src/assets/icon/dashboard-square-01.svg';
export { default as HomeIcon } from '@/src/assets/icon/home-05.svg';
export { default as MoneyIcon } from '@/src/assets/icon/money-remove-01.svg';
export { default as PakageIcon } from '@/src/assets/icon/package (1).svg';
export { default as ArrowRightIcon } from '@/src/assets/icon/arrow-right-01 (1).svg';
export { default as UserIcon } from '@/src/assets/icon/user-multiple.svg';
export { default as StoreIcon } from '@/src/assets/icon/store-location-02 (1).svg';
export { default as WareHouseIcon } from '@/src/assets/icon/warehouse.svg';
export { default as AnalyticsIcon } from '@/src/assets/icon/analytics-01.svg';
export { default as ArrowleftdownIcon } from '@/src/assets/icon/arrow-down-left-01.svg';
export { default as NotificationIcon } from '@/src/assets/icon/notification-02.svg';
export { default as IdeaIcon } from '@/src/assets/icon/idea-01.svg';
export { default as ArrowdownIcon } from '@/src/assets/icon/Arrowdown.svg';
export { default as BuildingIcon } from '@/src/assets/icon/elements (2).svg';
export { default as SwitchIcon } from '@/src/assets/icon/exchange-01 (1).svg';
export { default as SupportIcon } from '@/src/assets/icon/customer-service-01.svg';
export { default as UserIcon2 } from '@/src/assets/icon/User2.svg';
export { default as HelpIcon } from '@/src/assets/icon/help-circle.svg';
export { default as SuccessIcon } from '@/src/assets/icon/SuccessIcon.svg';
export { default as BgRotatingIcon } from '@/src/assets/icon/Repeat group 2.svg';
export { default as StockIcon } from '@/src/assets/icon/StockIcon.svg';
export { default as BackArrowIcon } from '@/src/assets/icon/arrow-left-01.svg';
export { default as UploadIcon } from '@/src/assets/icon/upload-02.svg';
export { default as DeleteIcon } from '@/src/assets/icon/delete-02.svg';
export { default as UploadIcon2 } from '@/src/assets/icon/uploadicon.svg';
export { default as ClipIcon } from '@/src/assets/icon/attachment.svg';
export { default as SendIcon } from '@/src/assets/icon/sent.svg';
export { default as ShieldIcon } from '@/src/assets/icon/shield-02.svg';
export { default as PageIcon } from '@/src/assets/icon/file-01.svg';
export { default as TelIcon } from '@/src/assets/icon/telephone.svg';
export { default as ChatIcon } from '@/src/assets/icon/chatting-01.svg';
export { default as CheckMarkIcon } from '@/src/assets/icon/checkmark-circle-03 (1).svg';
export { default as PackageReceiveIcon } from '@/src/assets/icon/package-receive.svg';
export { default as GreenCheckIcon } from '@/src/assets/icon/greenCheck.svg';
export { default as BlueCheckIcon } from '@/src/assets/icon/TopStatus.svg';
export { default as StarIcon } from '@/src/assets/icon/star.svg';
export { default as FilterIcon } from '@/src/assets/icon/filter.svg';
export { default as Store02Icon } from '@/src/assets/icon/store-03.svg';
export { default as CartIcon } from '@/src/assets/icon/shopping-cart-02.svg';

// Sidenav icons
export { default as SideHomeIcon } from '@/src/assets/icon/sidenavIcons/warehouse.svg';
export { default as SideProductIcon } from '@/src/assets/icon/sidenavIcons/product.svg';
export { default as SideSalesIcon } from '@/src/assets/icon/sidenavIcons/sales.svg';
export { default as SideCustomersIcon } from '@/src/assets/icon/sidenavIcons/customers.svg';
export { default as SideWarehouseIcon } from '@/src/assets/icon/sidenavIcons/warehouse2.svg';
export { default as SideVerificationIcon } from '@/src/assets/icon/sidenavIcons/verification.svg';
export { default as SideNumbersIcon } from '@/src/assets/icon/sidenavIcons/number.svg';
export { default as SideWalletIcon } from '@/src/assets/icon/sidenavIcons/wallet.svg';
export { default as SideInsightsIcon } from '@/src/assets/icon/sidenavIcons/insight.svg';
export { default as SideDevelopersIcon } from '@/src/assets/icon/sidenavIcons/developers.svg';
export { default as SideSettingsIcon } from '@/src/assets/icon/sidenavIcons/settings.svg';
export { default as SideHelpIcon } from '@/src/assets/icon/sidenavIcons/help-center.svg';
export { default as SideRcsIcon } from '@/src/assets/icon/sidenavIcons/rcs.svg';
export { default as SideGiftIcon } from '@/src/assets/icon/sidenavIcons/gift.svg';
export { default as SideAvatarIcon } from '@/src/assets/icon/sidenavIcons/Avatar.svg';

// Extra nav icons — reuse existing SVGs for new drawer sections
export { default as SideMarketplaceIcon } from '@/src/assets/icon/shopping-cart-02.svg';
export { default as SideFinanceIcon }     from '@/src/assets/icon/money-remove-01.svg';
export { default as SideReportsIcon }     from '@/src/assets/icon/analytics-01.svg';
export { default as SideStaffIcon }       from '@/src/assets/icon/user-multiple.svg';
export { default as SideInvoiceIcon }     from '@/src/assets/icon/file-01.svg';
export { default as SideSuppliersIcon }   from '@/src/assets/icon/store-03.svg';
