import './globals.css';
import type { Metadata } from 'next';
import { generalSans } from './fonts/font';

export const metadata: Metadata = {
  title: 'Vintran Inventory',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${generalSans.variable} h-full antialiased`}>
      <body className="h-screen flex flex-col">{children}</body>
    </html>
  );
}
