import './globals.css';
import type { Metadata } from 'next';
import { generalSans } from './fonts/font';
import { Toaster } from 'sonner';
import { AuthProvider } from '@/src/components/auth/AuthProvider';

export const metadata: Metadata = {
  title: 'Vintran Inventory',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${generalSans.variable} h-full antialiased`}>
      <body className="h-screen flex flex-col" suppressHydrationWarning>
        <AuthProvider>
          {children}
        </AuthProvider>
        <Toaster
          position="top-center"
          richColors
          closeButton
          toastOptions={{
            style: { fontFamily: 'var(--font-general-sans, sans-serif)' },
          }}
        />
      </body>
    </html>
  );
}
